/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tcrtrial;

public class Library {
    public boolean someLibraryMethod() {
        return true;
    }

    public String say() {
        return "hello";
    }
}
